name: budgetApp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  provider: ^4.3.3

  intl: ^0.16.1

  shared_preferences: ^0.5.12+4

  font_awesome_flutter: ^8.11.0
  flutter_svg: any

  path_provider: ^1.6.27
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.8.2
  build_runner: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/
